//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HistorianSyncTool.Properties
{
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.0.3.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase
    {
        private static Settings defaultInstance =
            (Settings)global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings());

        public static Settings Default => defaultInstance;

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string PrimaryHostname
        {
            get { return (string)this["PrimaryHostname"]; }
            set { this["PrimaryHostname"] = value; }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SecondaryHostname
        {
            get { return (string)this["SecondaryHostname"]; }
            set { this["SecondaryHostname"] = value; }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("*")]
        public string TagnameFilter
        {
            get { return (string)this["TagnameFilter"]; }
            set { this["TagnameFilter"] = value; }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("HistSync")]
        public string SyncTagName
        {
            get { return (string)this["SyncTagName"]; }
            set { this["SyncTagName"] = value; }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2025-01-01T00:00:00")]
        public global::System.DateTime StartDate
        {
            get { return (global::System.DateTime)this["StartDate"]; }
            set { this["StartDate"] = value; }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2025-01-01T00:00:00")]
        public global::System.DateTime EndDate
        {
            get { return (global::System.DateTime)this["EndDate"]; }
            set { this["EndDate"] = value; }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool GapAnalysisOnHistSync
        {
            get { return (bool)this["GapAnalysisOnHistSync"]; }
            set { this["GapAnalysisOnHistSync"] = value; }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ScheduleEnabled
        {
            get { return (bool)this["ScheduleEnabled"]; }
            set { this["ScheduleEnabled"] = value; }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("60")]
        public int ScheduleIntervalMinutes
        {
            get { return (int)this["ScheduleIntervalMinutes"]; }
            set { this["ScheduleIntervalMinutes"] = value; }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("24")]
        public int ScheduleEvalWindowHours
        {
            get { return (int)this["ScheduleEvalWindowHours"]; }
            set { this["ScheduleEvalWindowHours"] = value; }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Both")]
        public string ScheduleDirection
        {
            get { return (string)this["ScheduleDirection"]; }
            set { this["ScheduleDirection"] = value; }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("*")]
        public string ScheduleTagFilter
        {
            get { return (string)this["ScheduleTagFilter"]; }
            set { this["ScheduleTagFilter"] = value; }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ScheduleRunOnStartup
        {
            get { return (bool)this["ScheduleRunOnStartup"]; }
            set { this["ScheduleRunOnStartup"] = value; }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0001-01-01T00:00:00")]
        public global::System.DateTime ScheduleLastRunUtc
        {
            get { return (global::System.DateTime)this["ScheduleLastRunUtc"]; }
            set { this["ScheduleLastRunUtc"] = value; }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ScheduleUseTagList
        {
            get { return (bool)this["ScheduleUseTagList"]; }
            set { this["ScheduleUseTagList"] = value; }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ScheduleTagList
        {
            get { return (string)this["ScheduleTagList"]; }
            set { this["ScheduleTagList"] = value; }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool TagLinkEnabled
        {
            get { return (bool)this["TagLinkEnabled"]; }
            set { this["TagLinkEnabled"] = value; }
        }

        /// <summary>UI language: "En" or "De".</summary>
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("En")]
        public string Language
        {
            get { return (string)this["Language"]; }
            set { this["Language"] = value; }
        }

        /// <summary>Technical view: data tables, activity log, filters, per-direction copy
        /// buttons and batch counters. Off by default — the simple view is the product.</summary>
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AdvancedMode
        {
            get { return (bool)this["AdvancedMode"]; }
            set { this["AdvancedMode"] = value; }
        }

        /// <summary>
        /// The user has explicitly confirmed that an automatic repair may run right after
        /// startup. Auto-connect made that path reachable for the first time, so it is
        /// confirmed once rather than inherited silently from an old settings file.
        /// </summary>
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ScheduleStartupConfirmed
        {
            get { return (bool)this["ScheduleStartupConfirmed"]; }
            set { this["ScheduleStartupConfirmed"] = value; }
        }

        /// <summary>Connect to the saved servers automatically on startup.</summary>
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool AutoConnectOnStartup
        {
            get { return (bool)this["AutoConnectOnStartup"]; }
            set { this["AutoConnectOnStartup"] = value; }
        }
    }
}
