//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HistorianSyncTool.Properties
{
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.0.3.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase
    {
        private static Settings defaultInstance =
            (Settings)global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings());

        public static Settings Default => defaultInstance;

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string PrimaryHostname
        {
            get { return (string)this["PrimaryHostname"]; }
            set { this["PrimaryHostname"] = value; }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SecondaryHostname
        {
            get { return (string)this["SecondaryHostname"]; }
            set { this["SecondaryHostname"] = value; }
        }

        /// <summary>
        /// Server addresses that have connected successfully before, semicolon-separated,
        /// most recent first. Offered in both server dropdowns so a site with a handful of
        /// Historians picks instead of retyping.
        /// </summary>
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ServerHistory
        {
            get { return (string)this["ServerHistory"]; }
            set { this["ServerHistory"] = value; }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("*")]
        public string TagnameFilter
        {
            get { return (string)this["TagnameFilter"]; }
            set { this["TagnameFilter"] = value; }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("HistSync")]
        public string SyncTagName
        {
            get { return (string)this["SyncTagName"]; }
            set { this["SyncTagName"] = value; }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2025-01-01T00:00:00")]
        public global::System.DateTime StartDate
        {
            get { return (global::System.DateTime)this["StartDate"]; }
            set { this["StartDate"] = value; }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2025-01-01T00:00:00")]
        public global::System.DateTime EndDate
        {
            get { return (global::System.DateTime)this["EndDate"]; }
            set { this["EndDate"] = value; }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool GapAnalysisOnHistSync
        {
            get { return (bool)this["GapAnalysisOnHistSync"]; }
            set { this["GapAnalysisOnHistSync"] = value; }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ScheduleEnabled
        {
            get { return (bool)this["ScheduleEnabled"]; }
            set { this["ScheduleEnabled"] = value; }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("60")]
        public int ScheduleIntervalMinutes
        {
            get { return (int)this["ScheduleIntervalMinutes"]; }
            set { this["ScheduleIntervalMinutes"] = value; }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("24")]
        public int ScheduleEvalWindowHours
        {
            get { return (int)this["ScheduleEvalWindowHours"]; }
            set { this["ScheduleEvalWindowHours"] = value; }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Both")]
        public string ScheduleDirection
        {
            get { return (string)this["ScheduleDirection"]; }
            set { this["ScheduleDirection"] = value; }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("*")]
        public string ScheduleTagFilter
        {
            get { return (string)this["ScheduleTagFilter"]; }
            set { this["ScheduleTagFilter"] = value; }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ScheduleRunOnStartup
        {
            get { return (bool)this["ScheduleRunOnStartup"]; }
            set { this["ScheduleRunOnStartup"] = value; }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0001-01-01T00:00:00")]
        public global::System.DateTime ScheduleLastRunUtc
        {
            get { return (global::System.DateTime)this["ScheduleLastRunUtc"]; }
            set { this["ScheduleLastRunUtc"] = value; }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ScheduleUseTagList
        {
            get { return (bool)this["ScheduleUseTagList"]; }
            set { this["ScheduleUseTagList"] = value; }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ScheduleTagList
        {
            get { return (string)this["ScheduleTagList"]; }
            set { this["ScheduleTagList"] = value; }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool TagLinkEnabled
        {
            get { return (bool)this["TagLinkEnabled"]; }
            set { this["TagLinkEnabled"] = value; }
        }

        /// <summary>UI language: "En" or "De".</summary>
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("En")]
        public string Language
        {
            get { return (string)this["Language"]; }
            set { this["Language"] = value; }
        }

        /// <summary>Technical view: data tables, activity log, filters, per-direction copy
        /// buttons and batch counters. Off by default — the simple view is the product.</summary>
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AdvancedMode
        {
            get { return (bool)this["AdvancedMode"]; }
            set { this["AdvancedMode"] = value; }
        }

        /// <summary>
        /// The user has explicitly confirmed that an automatic repair may run right after
        /// startup. Auto-connect made that path reachable for the first time, so it is
        /// confirmed once rather than inherited silently from an old settings file.
        /// </summary>
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ScheduleStartupConfirmed
        {
            get { return (bool)this["ScheduleStartupConfirmed"]; }
            set { this["ScheduleStartupConfirmed"] = value; }
        }

        /// <summary>Connect to the saved servers automatically on startup.</summary>
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool AutoConnectOnStartup
        {
            get { return (bool)this["AutoConnectOnStartup"]; }
            set { this["AutoConnectOnStartup"] = value; }
        }

        /// <summary>
        /// True until this build has imported the settings of the previously installed version.
        /// Defaults to True, and a fresh user.config for a NEW version defaults it to True
        /// again — which is exactly the signal that an upgrade just happened.
        /// </summary>
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool SettingsUpgradeRequired
        {
            get { return (bool)this["SettingsUpgradeRequired"]; }
            set { this["SettingsUpgradeRequired"] = value; }
        }

        /// <summary>Historian login name, if the user chose to remember it. Empty = fall back to
        /// app.config, then to the Windows session. See <see cref="Services.HistorianCredentials"/>.</summary>
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string HistorianUser
        {
            get { return (string)this["HistorianUser"]; }
            set { this["HistorianUser"] = value; }
        }

        /// <summary>The password, encrypted with DPAPI for the current Windows user. Useless on
        /// another machine or to another user, and never present in the hand-out zip.</summary>
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string HistorianPasswordEnc
        {
            get { return (string)this["HistorianPasswordEnc"]; }
            set { this["HistorianPasswordEnc"] = value; }
        }

        /// <summary>
        /// Carry the previous version's saved settings into this build, once.
        ///
        /// User-scoped settings live in a per-VERSION folder
        /// (%LOCALAPPDATA%\HistorianSyncTool\...\&lt;version&gt;\user.config), so the moment
        /// AssemblyVersion changes, .NET starts from an empty file and every stored value is
        /// gone: both server addresses and the address history, the language, the Advanced
        /// toggle, and the whole scheduler configuration — which silently reverts to interval
        /// 60, direction Both and mask '*'. Nothing tells the user; the app simply looks
        /// factory-fresh after an update, and an unattended repair would run against defaults
        /// nobody chose.
        ///
        /// Upgrade() finds the newest previous version's file and imports it. It must run
        /// BEFORE anything reads a setting, so it is called first thing in Program.Main.
        /// </summary>
        public void UpgradeFromPreviousVersion()
        {
            if (!SettingsUpgradeRequired) return;
            try
            {
                Upgrade();
            }
            catch (global::System.Configuration.ConfigurationErrorsException ex)
            {
                // A corrupt or unreadable previous user.config must not stop the app starting.
                // Losing the old settings is bad; refusing to launch is worse.
                global::System.Diagnostics.Trace.TraceError(
                    "Could not import the previous version's settings: " + ex);
            }
            SettingsUpgradeRequired = false;
            Save();
        }
    }
}
